/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrattamentiIndexRouteImport } from './routes/trattamenti/index'
import { Route as TrattamentiSlugRouteImport } from './routes/trattamenti/$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiIndexRoute = TrattamentiIndexRouteImport.update({
  id: '/trattamenti/',
  path: '/trattamenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiSlugRoute = TrattamentiSlugRouteImport.update({
  id: '/trattamenti/$slug',
  path: '/trattamenti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/faq': typeof FaqRoute
  '/galleria': typeof GalleriaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/faq': typeof FaqRoute
  '/galleria': typeof GalleriaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
  '/trattamenti': typeof TrattamentiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/faq': typeof FaqRoute
  '/galleria': typeof GalleriaRoute
  '/prenota': typeof PrenotaRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/trattamenti/$slug': typeof TrattamentiSlugRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/faq'
    | '/galleria'
    | '/prenota'
    | '/privacy'
    | '/studio'
    | '/team'
    | '/trattamenti/$slug'
    | '/trattamenti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/faq'
    | '/galleria'
    | '/prenota'
    | '/privacy'
    | '/studio'
    | '/team'
    | '/trattamenti/$slug'
    | '/trattamenti'
  id:
    | '__root__'
    | '/'
    | '/contatti'
    | '/cookie'
    | '/faq'
    | '/galleria'
    | '/prenota'
    | '/privacy'
    | '/studio'
    | '/team'
    | '/trattamenti/$slug'
    | '/trattamenti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  FaqRoute: typeof FaqRoute
  GalleriaRoute: typeof GalleriaRoute
  PrenotaRoute: typeof PrenotaRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TeamRoute: typeof TeamRoute
  TrattamentiSlugRoute: typeof TrattamentiSlugRoute
  TrattamentiIndexRoute: typeof TrattamentiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/': {
      id: '/trattamenti/'
      path: '/trattamenti'
      fullPath: '/trattamenti/'
      preLoaderRoute: typeof TrattamentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$slug': {
      id: '/trattamenti/$slug'
      path: '/trattamenti/$slug'
      fullPath: '/trattamenti/$slug'
      preLoaderRoute: typeof TrattamentiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  FaqRoute: FaqRoute,
  GalleriaRoute: GalleriaRoute,
  PrenotaRoute: PrenotaRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TeamRoute: TeamRoute,
  TrattamentiSlugRoute: TrattamentiSlugRoute,
  TrattamentiIndexRoute: TrattamentiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
